export {
  AtomTable,
  AtomTableHeader,
  AtomTableBody,
  AtomTableFooter,
  AtomTableHead,
  AtomTableRow,
  AtomTableCell,
  AtomTableCaption,
  atomTableVariants,
  atomTableHeaderVariants,
  atomTableBodyVariants,
  atomTableRowVariants,
  atomTableHeadVariants,
  atomTableCellVariants,
  atomTableCaptionVariants,
} from './AtomTable';
