const NAME_REFERENCE_FONT_SIZE = 400;
const NAME_STAMP_STROKE_WIDTH_MAX = 20;
const NAME_STAMP_FONT_SIZE_MIN = 50;

const resolveMaxReferenceStrokeWidth = () => NAME_STAMP_STROKE_WIDTH_MAX * (NAME_REFERENCE_FONT_SIZE / NAME_STAMP_FONT_SIZE_MIN);

export { NAME_REFERENCE_FONT_SIZE, NAME_STAMP_FONT_SIZE_MIN, NAME_STAMP_STROKE_WIDTH_MAX, resolveMaxReferenceStrokeWidth };
