const NAME_STAMP_UV = { x: 0.25, y: 0.35 } as const;
const NAME_REFERENCE_FONT_SIZE = 100;
const NAME_REFERENCE_STROKE_WIDTH = 4;

export { NAME_REFERENCE_FONT_SIZE, NAME_REFERENCE_STROKE_WIDTH, NAME_STAMP_UV };
