export { DEFAULT_TEXT_CONFIGURATION } from './DEFAULT_TEXT_CONFIGURATION';
export { STEPS_CONFIGURATION } from './STEPS_CONFIGURATION';
export { FONTS_CONFIGURATION } from './FONTS_CONFIGURATION';
export { PALETTE_COLORS } from './PALETTE_COLORS';
