/** Corrects text/number orientation relative to the print UV space on the garment. */
const PRINT_UPLOAD_ROTATION_DEG = 90;

const NAME_REFERENCE_FONT_SIZE = 400;
const NAME_STAMP_STROKE_WIDTH_MAX = 20;
const NAME_STAMP_FONT_SIZE_MIN = 50;

// Gizmo chrome is authored in reference-stamp px but drawn at a fixed atlas scale so handles
// do not grow/shrink when the user changes fontSize (uNameScale).
const NAME_GIZMO_REFERENCE_BTN_HALF = 120;
const NAME_GIZMO_REFERENCE_BTN_OUTSET = 80;
const NAME_GIZMO_REFERENCE_FRAME_LINE_HALF = 4.5;
const NAME_GIZMO_REFERENCE_DASH_PERIOD = 46;
const NAME_GIZMO_BTN_FILL_COLOR = '#ffffff';
const NAME_GIZMO_BTN_ACTIVE_COLOR = '#dc2c6f';
const NAME_GIZMO_ICON_COLOR = '#1a1a1a';
const NAME_GIZMO_UI_FONT_SIZE = 80;
const NAME_GIZMO_UI_ATLAS_SCALE = NAME_GIZMO_UI_FONT_SIZE / NAME_REFERENCE_FONT_SIZE;

const NAME_GIZMO_BTN_HALF_ATLAS = NAME_GIZMO_REFERENCE_BTN_HALF * NAME_GIZMO_UI_ATLAS_SCALE;
const NAME_GIZMO_BTN_OUTSET_ATLAS = NAME_GIZMO_REFERENCE_BTN_OUTSET * NAME_GIZMO_UI_ATLAS_SCALE;
const NAME_GIZMO_FRAME_LINE_HALF_ATLAS = NAME_GIZMO_REFERENCE_FRAME_LINE_HALF * NAME_GIZMO_UI_ATLAS_SCALE;
const NAME_GIZMO_DASH_PERIOD_ATLAS = NAME_GIZMO_REFERENCE_DASH_PERIOD * NAME_GIZMO_UI_ATLAS_SCALE;

export {
  PRINT_UPLOAD_ROTATION_DEG,
  NAME_GIZMO_BTN_ACTIVE_COLOR,
  NAME_GIZMO_BTN_FILL_COLOR,
  NAME_GIZMO_BTN_HALF_ATLAS,
  NAME_GIZMO_ICON_COLOR,
  NAME_GIZMO_BTN_OUTSET_ATLAS,
  NAME_GIZMO_DASH_PERIOD_ATLAS,
  NAME_GIZMO_FRAME_LINE_HALF_ATLAS,
  NAME_GIZMO_REFERENCE_BTN_HALF,
  NAME_GIZMO_REFERENCE_BTN_OUTSET,
  NAME_GIZMO_REFERENCE_DASH_PERIOD,
  NAME_GIZMO_REFERENCE_FRAME_LINE_HALF,
  NAME_GIZMO_UI_ATLAS_SCALE,
  NAME_REFERENCE_FONT_SIZE,
  NAME_STAMP_FONT_SIZE_MIN,
  NAME_STAMP_STROKE_WIDTH_MAX,
};
