export {
  LOGO_ATLAS_REF_HEIGHT,
  LOGO_ATLAS_REF_WIDTH,
  LOGO_MARK_REF_WIDTH,
  LOGO_SCALE_MAX,
  LOGO_SCALE_MIN,
  LOGO_SLOT_COUNT,
  LOGO_UPLOAD_ROTATION_DEG,
  LOGO_VERTICAL_REF_HEIGHT,
} from './LOGO_STAMP_CONSTANTS';
