const PRINT_ATLAS_ASPECT = 4900 / 9331;
const PRINT_ATLAS_WIDTH = 4096;
const PRINT_ATLAS_HEIGHT = Math.round(PRINT_ATLAS_ASPECT * PRINT_ATLAS_WIDTH);

export { PRINT_ATLAS_ASPECT, PRINT_ATLAS_HEIGHT, PRINT_ATLAS_WIDTH };
